export const ADD_TODO = 'ADD_TODO';

export const EDIT_TODO_START = 'EDIT_TODO_START';

export const EDIT_TODO_COMPLETE = 'EDIT_TODO_COMPLETE';

export const DELETE_TODO_START = 'DELETE_TODO_START';

export const DELETE_TODO_COMPLETE = 'DELETE_TODO_COMPLETE';

export const GET_MOTIVATIONAL_QUOTES = 'GET_MOTIVATIONAL_QUOTES';

export const SWITCH_PAGE = 'SWITCH_PAGE';

export const SET_VISABLE_MODAL = 'SET_VISABLE_MODAL';

export const GET_SINGLE_TODO = 'GET_SINGLE_TODO';
