export const ADD_TODO = 'ADD_TODO';

export const EDIT_TODO = 'EDIT_TODO';

export const DELETE_TODO = 'DELETE_TODO';

export const GET_MOTIVATIONAL_QUOTES = 'GET_MOTIVATIONAL_QUOTES';

export const SWITCH_PAGE = 'SWITCH_PAGE';

export const SET_VISABLE_MODAL = 'SET_VISABLE_MODAL';
